export const SHEET_HELP = {
  attribute: {
    car: { title: "Carisma", subtitle: "CAR", body: "Sociabilidad, persuasion, intimidacion, seduccion y presencia." },
    des: { title: "Destreza", subtitle: "DES", body: "Rapidez, sigilo, maña, reflejos y equilibrio." },
    fue: { title: "Fuerza", subtitle: "FUE", body: "Vigor fisico, constitucion, empuje y resistencia corporal." },
    int: { title: "Inteligencia", subtitle: "INT", body: "Razonamiento, cultura, memoria, tecnica y conocimientos." },
    per: { title: "Percepcion", subtitle: "PER", body: "Sentidos, punteria, atencion y lectura del entorno." }
  },
  skill: {
    atletismo: { title: "Atletismo", subtitle: "DES", body: "Tiene que ver con la mayor parte de las acciones relacionadas con el movimiento físico, como correr, nadar, saltar, trepar o bailar.", details: ["En competencia con otros personajes, la dificultad siempre es la Agilidad del rival; si hay varios, usa la Agilidad más alta."] },
    auxilio: { title: "Auxilio", subtitle: "INT", body: "Sirve para poner en práctica conocimientos relativos a la salud, diagnosticar dolencias, recomendar medicamentos y tratamientos y aplicar primeros auxilios a otro personaje o al propio PJ si puede hacerlo.", details: ["Se usa Auxilio, no Observación, para examinar a alguien y determinar su salud, enfermedad o dolencia."] },
    conducir: { title: "Conducir", subtitle: "DES", body: "Se emplea para cabalgar o guiar cualquier montura o vehículo con presteza, diligencia y eficacia. En ciencia ficción incluye también naves espaciales.", details: ["En persecuciones, la dificultad es la Agilidad del rival; si hay varios, se resuelve contra cada rival por separado."] },
    conversacion: { title: "Conversación", subtitle: "CAR", body: "Se emplea para vencer confrontaciones de pareceres con argumentos racionales o emocionales, regatear precios e imponer los propios puntos de vista. También sirve para obtener información de forma franca y honesta.", details: ["La dificultad siempre es el Aplomo del PNJ interlocutor."] },
    cultura: { title: "Cultura", subtitle: "INT", body: "Engloba los saberes humanos razonables que no sean idiomas ni conocimiento del entorno inmediato: antropología, arqueología, historia, derecho, economía, arte, botánica, física, química, matemáticas, geología, geografía, música o literatura." },
    entorno: { title: "Entorno", subtitle: "PER", body: "Permite conocer datos concretos del entorno físico y humano habitual del personaje: topografía, localizaciones, recursos, historia, economía, organización política, costumbres, leyendas, etc.", details: ["La dificultad es baja para el entorno inmediato del personaje y alta para ámbitos mayores."] },
    fuerzaBruta: { title: "Fuerza bruta", subtitle: "FUE", body: "Se usa para acciones basadas exclusivamente en vigor corporal: romper una puerta, abrirse paso entre una multitud, remar con brío, empujar un vehículo averiado o librarse de una inmovilización.", details: ["En competencia, la dificultad siempre es la Agilidad del rival; si hay varios, usa la más alta."] },
    idiomaExtranjero1: { title: "Idioma extranjero I", subtitle: "INT", body: "Sirve para leer, escribir y comunicarse oralmente en una lengua distinta de la materna. Debe indicarse el idioma concreto, real o inventado.", details: ["Normalmente solo se tira en conversaciones prolongadas o técnicas, o al leer textos extensos. 1D indica apenas chapurrear unas decenas de frases."] },
    idiomaExtranjero2: { title: "Idioma extranjero II", subtitle: "INT", body: "Segunda habilidad de idioma extranjero. Si el PJ conoce una tercera lengua o más, su nivel se entiende igual al de esta segunda habilidad.", details: ["No se puede asignar ni 1D a la segunda habilidad si antes no se han asignado 2D o 3D a la primera."] },
    informacion: { title: "Información", subtitle: "INT", body: "Permite gestionar, recabar datos y operar sobre medios relacionados con la lectoescritura: buscar libros, navegar por Internet, manejar dispositivos electrónicos o hacerse una idea de un volumen o documento.", details: ["Para hackear sistemas informáticos se usa Información y no Mecánica; la dificultad mínima debería ser difícil."] },
    intimidacion: { title: "Intimidación", subtitle: "CAR", body: "Sirve para hacer que un PNJ sienta miedo mediante amenazas veladas o explícitas y se pliegue a los deseos del PJ, siempre que el DJ considere que es susceptible de ser presionado.", details: ["La dificultad siempre es el Aplomo del PNJ.", "También se usa al torturar para sonsacar información."] },
    lucha: { title: "Lucha", subtitle: "DES", body: "Se usa cuando un personaje combate desarmado o con armas cuerpo a cuerpo, ya sean de punta, cortantes o contundentes.", details: ["En combate, Lucha determina si se impacta. La dificultad es la Agilidad del objetivo, sea PJ o PNJ."] },
    mecanica: { title: "Mecánica", subtitle: "INT", body: "Sirve para utilizar, abrir, cerrar, manipular o arreglar máquinas, herramientas y mecanismos, desde cerraduras medievales hasta motores de taquiones.", details: ["También abre cajas de caudales o puertas blindadas si se dispone de equipo profesional; para cerraduras normales basta una ganzúa o recurso similar."] },
    memoria: { title: "Memoria", subtitle: "INT", body: "Se emplea para recordar casi cualquier cosa vista, escuchada o leída, especialmente caras, nombres, títulos, lugares y referencias. En general cubre lo que no encaja en Cultura o Entorno." },
    observacion: { title: "Observación", subtitle: "PER", body: "Se utiliza para registrar estancias, muebles o maletas, buscar activamente algo conocido pero no localizado y descubrir accidentalmente cosas ocultas que un observador atento podría ver.", details: ["Si se trata de descubrir a un PNJ escondido o emboscado, la dificultad es la Agilidad de ese PNJ."] },
    ocultacion: { title: "Ocultación", subtitle: "DES", body: "Sirve para esconder objetos, pero sobre todo para esconderse en entornos con cobertura: bosques, rocas, campos, calles, casas amuebladas o similares.", details: ["La dificultad siempre es la Perspicacia del PNJ que podría descubrir el objeto o al PJ escondido."] },
    oido: { title: "Oído", subtitle: "PER", body: "Permite escuchar conversaciones en susurros e identificar sonidos naturales o humanos. También sirve para calcular la distancia y dirección de una fuente sonora.", details: ["Para detectar la aproximación sigilosa de un PNJ, la dificultad es la Agilidad de ese PNJ."] },
    psicologia: { title: "Psicología", subtitle: "PER", body: "Se usa para detectar mentiras, pasiones y afinidades e interpretar correctamente las verdaderas intenciones de los personajes con los que se entra en relación.", details: ["Exige trato previo más o menos prolongado y no equivale a lectura mental.", "La dificultad siempre es el Aplomo del interlocutor."] },
    punteria: { title: "Puntería", subtitle: "PER", body: "Se emplea para cualquier acción que requiera puntería y precisión, incluidos proyectiles, armas de fuego y, en ciencia ficción, armas sónicas o láser.", details: ["En combate, Puntería determina si se impacta. La dificultad es la Agilidad del objetivo, sea PJ o PNJ."] },
    rastreo: { title: "Rastreo", subtitle: "PER", body: "Sirve para seguir vestigios de alguien o algo en terrenos susceptibles de rastreo: nieve, tierra, bosque o cualquier lugar con manchas, marcas o evidencias de paso.", details: ["Rastreo, y no Cultura, Entorno, Memoria u Observación, extrae datos de huellas: identidad, tiempo transcurrido, dirección, tamaño, corpulencia, naturaleza o estado físico."] },
    seduccion: { title: "Seducción", subtitle: "CAR", body: "Se utiliza para lograr que un PNJ se sienta atraído por el PJ, caer simpático y conseguir cosas razonables de los demás, como información, gracias al magnetismo personal.", details: ["La dificultad es el Aplomo del PNJ objetivo.", "Para culminar una seducción se requiere una segunda tirada a Aplomo + 3 tras un tiempo razonable."] },
    sigilo: { title: "Sigilo", subtitle: "DES", body: "Se emplea para no hacer ruido durante una acción, especialmente al andar o desplazarse. También puede usarse para hurtar algo.", details: ["La dificultad es la Perspicacia del PNJ que podría escuchar al PJ.", "En hurtos excepcionales puede requerir dos tiradas: aproximación y sustracción."] },
    simulacion: { title: "Simulación", subtitle: "CAR", body: "Sirve para enterarse de rumores y secretos sin hacerse notar, sonsacar información mediante ardides, mentir con eficacia o hacerse pasar por quien no se es. También cubre juegos no puramente de azar.", details: ["La dificultad es la Perspicacia del PNJ interlocutor u oponente; si hay varios, usa la más alta."] },
    supervivencia: { title: "Supervivencia", subtitle: "PER", body: "Engloba captura de pequeños animales, pesca manual, recolección de alimentos, refugios, búsqueda de agua potable y otras acciones para sobrevivir en espacios agrestes u hostiles.", details: ["La dificultad depende de la dureza y recursos del entorno.", "También puede usarse como Oler o Degustar para detectar propiedades, drogas o venenos en comida o bebida."] }
  },
  rule: {
    proezas: { title: "Proezas (SRD)", body: "Representan el empuje heroico del PJ. Al inicio de sesion se calculan como la mitad redondeada hacia abajo de FUE + INT, +3. Pueden gastarse para repetir dados de una tirada fallada, anadir 1D antes de tirar, mejorar temporalmente Agilidad/Aplomo/Perspicacia, aumentar dano o cancelar un critico enemigo.", details: ["No se puede superar 5D en una tirada de habilidad.", "El +1D por proeza es incompatible con Recuerdo cuando... en la misma tirada."] },
    agilidad: { title: "Agilidad", body: "Valor fijo y pasivo para resistir ataques, persecuciones y maniobras fisicas contra el personaje. Se calcula con 3 x dados de Atletismo + DES. En Ysystem3 evita tirar por el PNJ: el PJ tira contra este valor cuando corresponde." },
    aplomo: { title: "Aplomo", body: "Valor fijo y pasivo para resistir presion social, intimidacion, seduccion, miedo y situaciones que ponen a prueba la entereza. Se calcula con CAR + INT + 5 y tambien sirve de base para Estabilidad." },
    perspicacia: { title: "Perspicacia", body: "Valor fijo y pasivo para detectar enganos, ocultacion, sigilo y detalles relevantes cuando alguien actua contra el personaje. Se calcula con INT + PER + 5." },
    salud: { title: "Salud", body: "Mide la capacidad de resistir dano fisico. La Salud inicial se calcula con FUE x 2 + 10 + 1D6. Al bajar de ciertos umbrales se aplican penalizadores a las tiradas y pueden activarse tiradas de Resistencia fisica.", details: ["11 o menos: -1D.", "7 o menos: -2D.", "4 o menos: -3D.", "0 Salud: muerte salvo regla o tono de mesa que indique otra cosa."] },
    estabilidad: { title: "Estabilidad", body: "Mide la resistencia mental ante panico, horror, trauma o presion extrema. Se calcula con Aplomo + 5 + 1D6. Al cruzar umbrales se tiran pruebas de Resistencia mental; a 0 se produce una ruptura o locura permanente segun la escena." },
    resistenciaFisica: { title: "Resistencia fisica", body: "Valor objetivo para comprobar si el personaje se mantiene consciente al cruzar umbrales de Salud. Se calcula como 12 - FUE. La tirada se hace normalmente con 3D sin sumar atributo; si falla, el PJ cae inconsciente." },
    resistenciaMental: { title: "Resistencia mental", body: "Valor objetivo para comprobar si el personaje aguanta mentalmente al cruzar umbrales de Estabilidad. Se calcula como 12 - CAR. La tirada se hace normalmente con 3D; si falla, sufre una crisis temporal." },
    defectos: { title: "Defectos", body: "Los defectos permiten al DJ complicar una tirada cuando encajan con la ficcion. Un defecto grave obliga a repetir con -1D y el PJ gana 1 proeza. Un defecto leve permite forzar una repeticion una vez por sesion, sin dar proeza." },
    puntoGuion: { title: "Punto de guion", body: "Recurso narrativo para introducir un elemento, ventaja, contacto, detalle o giro razonable en la historia con aprobacion del DJ. No mejora directamente una tirada como una proeza: modifica la situacion narrativa. Normalmente se recupera al comienzo de una aventura o cuando el tono de campana lo permita." },
    ataque: { title: "Ataque (SRD)", body: "Los ataques se resuelven con Lucha o Punteria contra la Agilidad del objetivo. El dano depende del arma y normalmente suma el atributo indicado. Un critico duplica el dano e ignora armadura; una pifia puede dejar vendido al atacante o provocar una complicacion.", details: ["Las tiradas de habilidad nunca superan 5D.", "Las protecciones pueden reducir dano o aumentar la dificultad defensiva, segun sean armadura o escudo."] },
    danoReglado: { title: "Daño reglado", body: "Atajos para resolver fuentes de dano no procedentes de un ataque ordinario: caidas, asfixia, venenos, hambre, sed, quemaduras, sobreesfuerzos y riesgos ambientales. Ajusta la cantidad y automatismo segun la situacion de juego." },
    empeoramiento: { title: "Aprendizaje", body: "Ysystem3 permite adaptar la evolucion de los PJ al tono de la ambientacion. Usa este control para registrar cambios de atributo o deterioros pactados tras la aventura, especialmente en campanas donde la experiencia no solo mejora al personaje." }
  },
  section: {
    datos: { title: "Datos", body: "Identidad, perfil, profesion y motivacion del PJ." },
    arquetipos: { title: "Talentos", body: "Rasgos, talentos o notas mecanicas propias de la ambientacion." },
    pertenencias: { title: "Pertenencias", body: "Equipo, armas y talentos arrastrables." }
  }
};

export function helpEntry(type, key) {
  return SHEET_HELP[type]?.[key] ?? null;
}
